apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: balamurugansp/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
